// Extracts О компании / Контакты / blog posts from scratchpad HTML into
// src/content/pages-data.ts, and downloads blog images. Dev-only tool.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { parse } from "node-html-parser";

const SRC =
  "/tmp/user/1000/claude-1000/-home-hunt-Documents-Ubuntu-AGY-ai-website-cloner-template/9a156f73-fb4b-4bea-8048-74a3bffd4cd3/scratchpad/pages";

const STOP = /Отзывы|Вопрос-ответ|Популярные вопросы|Оставить заявку|Мы занимаемся авто|Похожие записи|Читайте также/i;
const NOISE =
  /Узнайте стоимость своего авто|Получите максимальную сумму|^Марка автомобиля$|^Модель автомобиля$|^Год выпуска$|^Ваш телефон$|^Дополнительная информация$|^Узнать стоимость$/i;
const norm = (s) => s.replace(/\s+/g, " ").trim();

function collect(html) {
  const root = parse(html);
  const content = root.querySelector("#Content") || root;
  const nodes = content.querySelectorAll("h1,h2,h3,h4,p,ul,ol");
  let title = "";
  const blocks = [];
  for (const el of nodes) {
    const tag = el.tagName.toLowerCase();
    if (el.closest("form")) continue;
    const txt = norm(el.text);
    if (/h[1-4]/.test(tag)) {
      if (!txt || NOISE.test(txt)) continue;
      if (STOP.test(txt)) break;
      if (tag === "h1") {
        title = txt;
        continue;
      }
      blocks.push({ t: "h", text: txt });
      continue;
    }
    if (tag === "ul" || tag === "ol") {
      const lis = el.childNodes
        .filter((c) => c.tagName === "LI")
        .map((li) => norm(li.text))
        .filter((x) => x.length > 1 && !NOISE.test(x));
      if (lis.length) blocks.push({ t: "list", items: lis });
      continue;
    }
    if (tag === "p") {
      if (el.closest("ul") || el.closest("ol")) continue;
      if (txt.length < 2 || NOISE.test(txt)) continue;
      blocks.push({ t: "p", text: txt });
    }
  }
  return { title, blocks };
}

function featuredImage(html) {
  const root = parse(html);
  const content = root.querySelector("#Content") || root;
  for (const img of content.querySelectorAll("img")) {
    const src = img.getAttribute("src") || "";
    if (src.includes("/uploads/") && !/logo|favicon/i.test(src)) {
      return src.replace(/-\d+x\d+(\.\w+)$/, "$1"); // strip size suffix → full image
    }
  }
  return null;
}

// blocks → {t:"p"|"list"} only (drop headings for h; keep as content) — actually keep h
const about = collect(await readFile(`${SRC}/okomp.html`, "utf8"));
const contacts = collect(await readFile(`${SRC}/kontakty.html`, "utf8"));

const POSTS = [
  ["kak-prodat-avto-po-doverennosti", "Как продать авто по доверенности"],
  ["kak-prodat-avto-po-tehpasportu", "Как продать авто по техпаспорту"],
];

const blogPosts = [];
const imagesToDownload = [];
for (const [slug, label] of POSTS) {
  const html = await readFile(`${SRC}/post-${slug}.html`, "utf8");
  const { title, blocks } = collect(html);
  const remote = featuredImage(html);
  const local = `/images/blog/${slug}.jpg`;
  if (remote) imagesToDownload.push([remote, local]);
  blogPosts.push({ slug, title: title || label, image: remote ? local : null, blocks });
}

// download blog images
for (const [remote, local] of imagesToDownload) {
  try {
    const res = await fetch(remote, { headers: { "User-Agent": "Mozilla/5.0" } });
    if (!res.ok) throw new Error("HTTP " + res.status);
    const buf = Buffer.from(await res.arrayBuffer());
    const dest = join("public", local);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, buf);
    console.log(`img ✓ ${local} (${(buf.length / 1024).toFixed(0)}kb)`);
  } catch (e) {
    console.log(`img ✗ ${local}: ${e.message}`);
  }
}

const banner = `// AUTO-GENERATED by scripts/extract-pages.mjs — content from avtocare.com.ua\nimport type { TextPageData, BlogPost } from "@/types";\n\n`;
const out =
  banner +
  `export const ABOUT_PAGE: TextPageData = ${JSON.stringify(about, null, 2)};\n\n` +
  `export const CONTACTS_PAGE: TextPageData = ${JSON.stringify(contacts, null, 2)};\n\n` +
  `export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(blogPosts, null, 2)};\n`;
await writeFile("src/content/pages-data.ts", out, "utf8");
console.log(
  `about=${about.blocks.length} contacts=${contacts.blocks.length} posts=${blogPosts.map((p) => p.blocks.length)}`,
);
console.log("written src/content/pages-data.ts");
